Add SSL support for Remote.Hosting
akkadotnet/Akka.Hosting pull request #345
Opened 2023-08-01 16:36 UTC by Arkatufus

Fixes #327

## Changes
* Add plugable transport options to `RemoteOptions`
* Add SSL options to DotNetty transport

NOTE: this breaks MS.Ext.Configuration binding because the transport list has to be based on an abstract class.

2023-08-01 16:46 UTC, Aaronontheweb commented
> NOTE: this breaks MS.Ext.Configuration binding because the transport list has to be based on an abstract class.

in that case, might be better off not doing this until we actually need additional transports.

2023-08-01 16:50 UTC, Arkatufus commented
Updated the PR comment to explain why configuration binding doesn't work

2023-08-01 18:28 UTC, Aaronontheweb requested changes
Left some thoughts

2023-08-01 18:28 UTC, Aaronontheweb commented on src/Akka.Hosting.API.Tests/verify/CoreApiSpec.ApproveRemoting.verified.txt
> +    public sealed class DotNettyUdpTransportOptions : Akka.Remote.Hosting.DotNettyTransportOptions
Remove - not supported in Akka.Remote and most likely won't be.

2023-08-01 18:28 UTC, Aaronontheweb commented on src/Akka.Hosting.API.Tests/verify/CoreApiSpec.ApproveRemoting.verified.txt
> +        public System.Collections.Generic.List<Akka.Remote.Hosting.RemoteTransportOptions> EnabledTransports { get; set; }
You know, I'm thinking that even though we could support this - it's probably a footgun for 99.9999999999999% of users. Make super-users use HOCON if they want this feature.

2023-08-01 18:28 UTC, Aaronontheweb commented on src/Akka.Hosting.API.Tests/verify/CoreApiSpec.ApproveRemoting.verified.txt
> +    public sealed class SslCertificateOptions
LGTM

2023-08-03 16:29 UTC, Arkatufus commented
Remove multi-transport support

2023-08-03 18:13 UTC, Aaronontheweb approved these changes
LGTM

2023-08-03 18:13 UTC, merged