Add ILoggerFactory logger support
akkadotnet/Akka.Hosting pull request #72
Opened 2022-07-01 16:37 UTC by Arkatufus

Fixes #61

## Changes
- Add support to route Akka.NET logs to ILogger

2022-07-01 16:38 UTC, Arkatufus commented on src/Akka.Hosting/Logging/LoggerFactoryLogger.cs
> +        private const string DefaultMessageFormat = "[{{Timestamp:{0}}}][{{SourceContext}}][{{LogSource}}][{{ActorPath}}][{{Thread:0000}}]: {{Message}}";
I'm not sure if this is the best way to format the string, I'm open to suggestions.

2022-07-06 12:26 UTC, Aaronontheweb commented on src/Akka.Hosting/Logging/AkkaLoggerFactoryExtensions.cs
> +        public static AkkaConfigurationBuilder WithLoggerFactoryLogger(
I'd rename this to `WithLoggerFactory`

2022-07-08 15:36 UTC, Aaronontheweb requested changes
Overall looks really good, but:

- Needs some unit tests
- Have some other minor changes around class naming et al to consider.

2022-07-08 15:37 UTC, Aaronontheweb commented on src/Akka.Hosting/Logging/AkkaLoggerFactoryExtensions.cs
> +                var logger = extSystem.SystemActorOf(
Needs to be under `/system` or we lose all output from everything else once `/user` actors shutdown.

2022-07-08 15:39 UTC, Aaronontheweb commented
I'm also considering whether or not this should be instantiated through the normal `Logger` setup in Akka.NET in order to make sure this actor is kept alive when other `/system` actors are shutting down... That'd require:

1. A new `Setup` type which accepts the `ILoggerFactory`
2. A separate initiator actor that grabs that `Setup` and uses it to register the logger
3. A separate NuGet package.

Probably total overkill - as long as we unit test this setup **and add a sample that uses it inside Akka.Cluster** so Akka.Remote shutdown events can be observed, I think that should be fine. Does that make sense @Arkatufus ?

2022-07-18 12:17 UTC, Aaronontheweb approved these changes
Looks good to me - we night need to change things down the road depending on user feedback, but I think we should ship this as-is.

2022-07-18 12:17 UTC, Aaronontheweb commented on src/Akka.Hosting/Logging/AkkaLoggerFactoryExtensions.cs
> +        public static AkkaConfigurationBuilder AddLoggerFactory(this AkkaConfigurationBuilder builder)
I want to rename this method but I honestly can't think of a better one. `AddMsftLogger` ?

2022-07-18 12:18 UTC, merged